### PR TITLE
AUTO-1860 Use Dexory driver submodule

### PR DESCRIPTION
**Pull request by doisyg**
Addressing https://github.com/botsandus/auto-rslidar-sdk/pull/3#issuecomment-1863086744

### CODE REVIEW

**Comment by nachovizzo** [comment]
@doisyg which original branch  `dex` is tracking? Is not the same branch you used for testing FYI :)

Does not seem to change much... but worth mentioning 
```diff
diff --git a/src/rs_driver/driver/decoder/decoder_RSBP.hpp b/src/rs_driver/driver/decoder/decoder_RSBP.hpp
index 0704a96..b5b38b1 100644
--- a/src/rs_driver/driver/decoder/decoder_RSBP.hpp
+++ b/src/rs_driver/driver/decoder/decoder_RSBP.hpp
@@ -102,7 +102,6 @@ protected:
 
   template <typename T_BlockIterator>
   bool internDecodeMsopPkt(const uint8_t* pkt, size_t size);
-  bool reversal_;
 };
 
 template <typename T_PointCloud>
@@ -177,12 +176,7 @@ inline void DecoderRSBP<T_PointCloud>::decodeDifopPkt(const uint8_t* packet, siz
 {
   const RSBPDifopPkt& pkt = *(const RSBPDifopPkt*)(packet);
   this->template decodeDifopCommon<RSBPDifopPkt>(pkt);
-  if(pkt.reserved_2[0])
-  {
-    reversal_ = true;
-  }else{
-    reversal_ = false;
-  }
+
   this->echo_mode_ = getEchoMode (pkt.return_mode);
   this->split_blks_per_frame_ = (this->echo_mode_ == RSEchoMode::ECHO_DUAL) ? 
     (this->blks_per_frame_ << 1) : this->blks_per_frame_;
@@ -282,11 +276,7 @@ inline bool DecoderRSBP<T_PointCloud>::internDecodeMsopPkt(const uint8_t* packet
       int32_t angle_horiz_final = this->chan_angles_.horizAdjust(chan, angle_horiz);
 
       float distance = ntohs(channel.distance) * this->const_param_.DISTANCE_RES;
-      if(reversal_)
-      {
-          angle_horiz_final = 36000 - angle_horiz_final;
-          angle_horiz = 36000 - angle_horiz;
-      }
+
       if (this->distance_section_.in(distance) && this->scan_section_.in(angle_horiz_final))
       {
         float x =  distance * COS(angle_vert) * COS(angle_horiz_final) + this->mech_const_param_.RX * COS(angle_horiz);
diff --git a/src/rs_driver/driver/decoder/decoder_RSM1.hpp b/src/rs_driver/driver/decoder/decoder_RSM1.hpp
index 1f5d257..9cee1e8 100644
--- a/src/rs_driver/driver/decoder/decoder_RSM1.hpp
+++ b/src/rs_driver/driver/decoder/decoder_RSM1.hpp
@@ -304,11 +304,6 @@ inline bool DecoderRSM1<T_PointCloud>::decodeMsopPkt(const uint8_t* packet, size
     this->prev_point_ts_ = point_time;
   }
 
-  if (split_strategy_.maxSeq() == pkt_seq)
-  {
-    this->cb_split_frame_(this->const_param_.LASER_NUM, this->cloudTs());
-  }
-
   this->prev_pkt_ts_ = pkt_ts;
   return ret;
 }
diff --git a/src/rs_driver/driver/decoder/section.hpp b/src/rs_driver/driver/decoder/section.hpp
index 969d481..07e0d2e 100644
--- a/src/rs_driver/driver/decoder/section.hpp
+++ b/src/rs_driver/driver/decoder/section.hpp
@@ -42,10 +42,10 @@ class AzimuthSection
 public:
   AzimuthSection(int32_t start, int32_t end)
   {
-    full_round_ = _round (end - start) == 0;
+    full_round_ = (start == 0) && (end == 36000);
 
-    start_ = _round (start);
-    end_ = _round (end);
+    start_ = start % 36000;
+    end_ = end % 36000;
     cross_zero_ = (start_ > end_);
   }
 
@@ -67,13 +67,6 @@ public:
 #ifndef UNIT_TEST
 private:
 #endif
-
-  static
-  int32_t _round(int32_t value)
-  {
-      return (value % 36000 + 36000) % 36000;
-  }
-
   bool full_round_;
   int32_t start_;
   int32_t end_;
diff --git a/src/rs_driver/driver/decoder/split_strategy.hpp b/src/rs_driver/driver/decoder/split_strategy.hpp
index 43ff2de..e8200f5 100644
--- a/src/rs_driver/driver/decoder/split_strategy.hpp
+++ b/src/rs_driver/driver/decoder/split_strategy.hpp
@@ -114,7 +114,7 @@ class SplitStrategyBySeq
 public:
 
   SplitStrategyBySeq()
-    : prev_seq_(0), max_seq_(0), looped_(false)
+    : prev_seq_(0)
   {
     setSafeRange();
   }
@@ -123,16 +123,10 @@ public:
   {
     bool split = false;
 
-    if (seq > max_seq_)
-    {
-        max_seq_ = seq;
-    }
-
     if (seq < safe_seq_min_) // rewind
     {
       prev_seq_ = seq;
       split = true;
-      looped_ = true;
     }
     else if (seq < prev_seq_)
     {
@@ -154,12 +148,6 @@ public:
     return split;
   }
 
-  uint16_t maxSeq()
-  {
-      return (looped_ ? max_seq_ : 0);
-  }
-  
-
 #ifndef UNIT_TEST
 private:
 #endif
@@ -175,9 +163,6 @@ private:
   uint16_t prev_seq_;
   uint16_t safe_seq_min_;
   uint16_t safe_seq_max_;
-
-  uint16_t max_seq_;
-  bool looped_;
 };
 
 }  // namespace lidar
diff --git a/src/rs_driver/driver/lidar_driver_impl.hpp b/src/rs_driver/driver/lidar_driver_impl.hpp
index 439ebf3..f380123 100644
--- a/src/rs_driver/driver/lidar_driver_impl.hpp
+++ b/src/rs_driver/driver/lidar_driver_impl.hpp
@@ -405,6 +405,10 @@ void LidarDriverImpl<T_PointCloud>::splitFrame(uint16_t height, double ts)
     cb_put_cloud_(cloud);
     decoder_ptr_->point_cloud_ = getPointCloud();
   }
+  else
+  {
+    runExceptionCallback(Error(ERRCODE_ZEROPOINTS));
+  }
 }
 
 template <typename T_PointCloud>
diff --git a/test/section_test.cpp b/test/section_test.cpp
index 8c3c189..2369d41 100644
--- a/test/section_test.cpp
+++ b/test/section_test.cpp
@@ -5,18 +5,9 @@
 
 using namespace robosense::lidar;
 
-TEST(TestAzimuthSection, round)
-{
-  ASSERT_EQ(AzimuthSection::_round(0), 0);
-  ASSERT_EQ(AzimuthSection::_round(36000), 0);
-  ASSERT_EQ(AzimuthSection::_round(-36000), 0);
-}
-
 TEST(TestAzimuthSection, ctorFull)
 {
   AzimuthSection sec(0, 36000);
-  ASSERT_TRUE(sec.full_round_);
-
   ASSERT_TRUE(sec.in(0));
   ASSERT_TRUE(sec.in(10));
   ASSERT_TRUE(sec.in(36000));
@@ -25,8 +16,6 @@ TEST(TestAzimuthSection, ctorFull)
 TEST(TestAzimuthSection, ctor)
 {
   AzimuthSection sec(10, 20);
-  ASSERT_FALSE(sec.full_round_);
-
   ASSERT_EQ(sec.start_, 10);
   ASSERT_EQ(sec.end_, 20);
 
```

**Comment by doisyg** [comment]
Hum, copy of `dev_opt`, which is the one I tested against locally on A5. Something must have jumped in the PR process

**Comment by scheunemann** [comment]
This is why we don't use submodules.

**Comment by doisyg** [comment]
> This is why we don't use submodules.

I was tempted to make that comment, but I am happy that I let you the pleasure of doing it

**Review by scheunemann — APPROVED** [review]
Tested on Arri-5 and Arri-3 (making sure all is set up with `git pull --recurse-submodules`) and I can't see a difference. Only tested navigation and visual inspected. I got a few time delocalised, but I can't really pin it to the BPearl directly. I am a little suspicious but I think it is good to go into master and we put it on a robot doing nightly runs. I will also ask @ajsampathk to break it next week :)

**Pull request merged**
