### PR TITLE
AUTO-236 add back_right

### PR DESCRIPTION
**Pull request by doisyg**
For https://botsandus.atlassian.net/browse/AUTO-236
Tested on the hardware
Screenshot from 2022-11-03 16-44-02

### CODE REVIEW

**Comment by scheunemann** [comment]
Cool picture. The two clouds looks a bit out of alignment than I had anticipated. Is that constant? Is that what you expected or do we need to measure the lidars position properly?

**Comment by doisyg** [comment]
Hard to say for sure with the picture, we should check properly the mounting but they are changing base very soon anyway

**Comment by scheunemann** [comment]
> Hard to say for sure with the picture, we should check properly the mounting but they are changing base very soon anyway

That was just out of curiosity and to get your opinion about the looks. From my point of view it looks off, in a way that the lidars yaw is off by a degree or so. Maybe even the pitch. Nothing to do, I really like that you put the testing picture here 👍🚀

**Comment by doisyg** [comment]
Good eye, definitely some yaw

**Review by kaichie — APPROVED** [review]
:100:

**Pull request merged**
